name: Deploy to VPS
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: 
      name: production
      url: https://fuminshou.online/
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd dev/personal-website
            eval $(ssh-agent -s)
            echo "${{ secrets.GH_DEPLOY_KEY }}" | ssh-add -
            git pull origin master
            pnpm install --frozen-lockfile
            pnpm run build
            pm2 reload personal-website
            cd src/
            node index.js
